# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

stage: Initial tests

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of
# packages that can be included can be found here:
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - EVENT_TYPE='pull_request push'
        - CONDA_DEPENDENCIES='scipy matplotlib re reproject'
        - CONDA_CHANNELS='astropy-ci-extras astropy'
        - SETUP_XVFB=True
        - ASTROPY_USE_SYSTEM_PYTEST=1

        # PEP8 errors/warnings:
        # E101 - mix of tabs and spaces
        # W191 - use of tabs
        # W291 - trailing whitespace
        # W292 - no newline at end of file
        # W293 - trailing whitespace
        # W391 - blank line at end of file
        # E111 - 4 spaces per indentation level
        # E112 - 4 spaces per indentation level
        # E113 - 4 spaces per indentation level
        # E502 - the backslash is redundant between brackets
        # E722 - do not use bare except
        # E901 - SyntaxError or IndentationError
        # E902 - IOError
        - FLAKE8_OPT="--select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E502,E722,E901,E902"

stages:
   - name: Initial tests
   - name: Test docs, astropy dev, and without optional dependencies
   - name: Tests with other Python/Numpy versions
   - name: Cron tests
     if: type = cron

matrix:
    # Don't wait for allowed failures
    fast_finish: true

    include:
        - env: PYTHON_VERSION=2.7 SETUP_CMD='egg_info'
        - env: PYTHON_VERSION=3.4 SETUP_CMD='egg_info'
        - env: PYTHON_VERSION=3.5 SETUP_CMD='egg_info'
        - env: PYTHON_VERSION=3.6 SETUP_CMD='egg_info'

        # Do a PEP8/pyflakes test with flake8
        - env: MAIN_CMD="flake8 astroimtools --count $FLAKE8_OPT" SETUP_CMD=''

        - env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - stage: Test docs, astropy dev, and without optional dependencies
          env: PYTHON_VERSION=2.7 SETUP_CMD='build_docs -w'
               CONDA_DEPENDENCIES='scipy matplotlib jupyter'

        - stage: Test docs, astropy dev, and without optional dependencies
          env: SETUP_CMD='build_docs -w'
               CONDA_DEPENDENCIES='scipy matplotlib jupyter'
               EVENT_TYPE='pull_request push cron'

        # Now try Astropy dev and LTS versions with the latest Python.
        # We disable LTS testing until astropy 3.0 is out, as the current
        # stable is also the LTS
        - stage: Test docs, astropy dev, and without optional dependencies
          env: ASTROPY_VERSION=development
               EVENT_TYPE='pull_request push cron'

        #- stage: Test docs, astropy dev, and without optional dependencies
        #  os: linux
        #  env: PYTHON_VERSION=3.5 ASTROPY_VERSION=lts

        # Try with optional dependencies disabled
        - stage: Test docs, astropy dev, and without optional dependencies
          env: PYTHON_VERSION=2.7

        - stage: Test docs, astropy dev, and without optional dependencies
          env: PYTHON_VERSION=3.6

        # Try older python and numpy versions. Since we can assume
        # that the Numpy developers have taken care of testing Numpy
        # with different versions of Python, we can vary Python and
        # Numpy versions at the same time.
        - stage: Tests with other Python/Numpy versions
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.9
               PIP_DEPENDENCIES='pytest>=3.1'

        - stage: Tests with other Python/Numpy versions
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.10

        - stage: Tests with other Python/Numpy versions
          env: NUMPY_VERSION=1.11

        - stage: Tests with other Python/Numpy versions
          env: NUMPY_VERSION=1.12

        - stage: Tests with other Python/Numpy versions
          env: NUMPY_VERSION=1.13

        # Try numpy pre-release
        - stage: Tests with other Python/Numpy versions
          env: NUMPY_VERSION=prerelease
               EVENT_TYPE='pull_request push cron'

        # Try MacOS X
        - stage: Cron tests
          os: osx
          env: SETUP_CMD='test' EVENT_TYPE='cron'

    allow_failures:
        - env: NUMPY_VERSION=prerelease
               EVENT_TYPE='pull_request push cron'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
   - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == *--coverage* ]]; then
          coveralls --rcfile='astroimtools/tests/coveragerc';
      fi
